title: # Haikyuu; a learning course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     # Haikyuu 
  repo:     # lab-starter

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before: 
type: respond
with: 01_first-response.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: # The first Arc
  description: # What led Karasuno to the first match against Aoba Johsai. 
  event: # https://haikyuu.fandom.com/wiki/Haikyuu!!_Wiki
  actions: # issue_commented.created
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
# - title: # The second arc. 
#  description: # what led Karasuno to beat Aoba Johsai the second time around. 
#  event: # https://haikyuu.fandom.com/wiki/Haikyuu!!_Wiki
#  actions: # issue_commented.created
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
# - title: # the third arc
#  description: # What led Karasuno to beat Shiratorizawa. 
#  event: # https://haikyuu.fandom.com/wiki/Haikyuu!!_Wiki
#  actions: # issue_commented.created
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
# - title: # the fourth arc. 
#  description: # What led Karasuno to play Inarizaki. 
#  event: # https://haikyuu.fandom.com/wiki/Haikyuu!!_Wiki
#  actions: # issue_commented.created
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
# - title: # The fifth arc, leading to the final arc. 
#  description: # what led karasuno to lose their first nationals. 
#  event: # https://haikyuu.fandom.com/wiki/Haikyuu!!_Wiki
#  actions: # issue_commented.created
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

